version: "3"
services:
  db:
    build: ./PostgresAlpine
    image: 192.168.43.2:5000/postgres:9.4-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - PostgresAlpine/db.env
  web:
    build: ./PayaraMicro
    image: 192.168.43.2:5000/payara/micro:4.181
    ports:
      - "8080:8081"
    #volumes:
        #- $HOME/img:/opt/payara/img/tmp/
    depends_on:
      - db 
volumes:
  db-data:
